Fractal\BlogBundle\Entity\Image:
  type: entity
  repositoryClass: Fractal\BlogBundle\Entity\Image
  table: images
  id:
    id:
      type:         integer
      generator:    { strategy: AUTO }
  fields:
    file:
      type:         string
      length:       100
    updated:        # changed when files are uploaded, to force preUpdate and postUpdate to fire
      type:         datetime
      nullable:     true
    # ... other fields ...
  lifecycleCallbacks:
      prePersist:   [ lifecycleFileUpload ]
      preUpdate:    [ lifecycleFileUpload ]