blog_homepage:
    pattern:  /
    defaults: { _controller: BlogBundle:Blog:Index }

blog_post:
    pattern:  /post/{slug}
    defaults: { _controller: BlogBundle:Blog:ShowPost }

blog_moreposts:
    pattern:  /moreposts
    defaults: { _controller: BlogBundle:Blog:MorePosts }

