user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user/

guest_book:
    resource: "@GuestBookBundle/Resources/config/routing.yml"
    prefix:   /guest/

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin